<?php

namespace baykit\bayserver\docker\fcgi;

interface FcgParams {
    const PATH = "PATH";
    const CONTEXT_DOCUMENT_ROOT = "CONTEXT_DOCUMENT_ROOT";
    const CONTEXT_PREFIX = "CONTEXT_PREFIX";
    const CONTENT_TYPE = "CONTENT_TYPE";
    const CONTENT_LENGTH = "CONTENT_LENGTH";
    const DOCUMENT_ROOT = "DOCUMENT_ROOT";
    const GATEWAY_INTERFACE = "GATEWAY_INTERFACE";
    const HTTP_ACCEPT = "HTTP_ACCEPT";
    const HTTP_ACCEPT_ENCODING = "HTTP_ACCEPT_ENCODING";
    const HTTP_ACCEPT_LANGUAGE = "HTTP_ACCEPT_LANGUAGE";
    const HTTP_CACHE_CONTROL = "HTTP_CACHE_CONTROL";
    const HTTP_COOKIE = "HTTP_COOKIE";
    const HTTP_CONNECTION = "HTTP_CONNECTION";
    const HTTP_HOST = "HTTP_HOST";
    const HTTP_USER_AGENT = "HTTP_USER_AGENT";
    const HTTP_UPGRADE_INSECURE_REQUESTS = "HTTP_UPGRADE_INSECURE_REQUESTS";
    const QUERY_STRING = "QUERY_STRING";
    const REMOTE_ADDR = "REMOTE_ADDR";
    const REQUEST_SCHEME = "REQUEST_SCHEME";
    const REQUEST_URI = "REQUEST_URI";
    const REMOTE_PORT = "REMOTE_PORT";
    const REQUEST_METHOD = "REQUEST_METHOD";
    const SCRIPT_NAME = "SCRIPT_NAME";
    const SCRIPT_FILENAME = "SCRIPT_FILENAME";
    const SERVER_ADDR = "SERVER_ADDR";
    const SERVER_ADMIN = "SERVER_ADMIN";
    const SERVER_NAME = "SERVER_NAME";
    const SERVER_PORT = "SERVER_PORT";
    const SERVER_PROTOCOL = "SERVER_PROTOCOL";
    const SERVER_SIGNATURE = "SERVER_SIGNATURE";
    const SERVER_SOFTWARE = "SERVER_SOFTWARE";
    const UNIQUE_ID = "UNIQUE_ID";
    const X_FORWARDED_FOR = "X-Forwarded-For";
    const X_FORWARDED_PROTO = "X-Forwarded-Proto";
    const X_FORWARDED_PORT = "X-Forwarded-Port";
}